### ISSUE TITLE
spotify play list widget

### ISSUE THREAD

**Issue by leslie-alldridge** [kakapo-2018/GYST#4]
1. works fine for a static playlist
2. decided to stash URLs in database
3. with auth it works to gather users playlists but this is going to be a stretch goal instead

current status - when stretch goal is approved to go ahead, we can look into saying database URL's for each user and allowing them to select a specific playlist

**Comment by leslie-alldridge** [comment]
added into a card component so it's mobile friendly

**Comment by lukechadwick** [comment]
More or less working though doesn't scale vertically

**Comment by leslie-alldridge** [comment]
happy with it atm going to close up
